### ISSUE TITLE
[DISCUSSION] Dataset downloading in 2.0

### ISSUE THREAD

**Issue by aneesh-joshi** [NTSC-Community/MatchZoo#230]
This issue is for discussing how datasets should be downloaded in 2.0

I had made a python script to download the data sets in https://github.com/faneshion/MatchZoo/pull/223 using `request`

However, these were the comments from @bwanglzu :

>We haven't discussed how to download such data yet, but I would not create a data directory and use some scripts there.
Checkout gluon-nlp, they provided some elegant ways to create data set.
Also, keras provided a dataset package to do such things.
I hope 2.0 is able to get rid of all the scripts, and make everything clean & programmable. Also, adding scripts will further reduce our code quality (we miss unit testing, PEP8, documentation) and increase technique debts.

With respect to the above, I would also like to recommend [gensim-data](https://github.com/RaRe-Technologies/gensim-data) as a good way of getting datasets.

**Comment by bwanglzu** [comment]
through it's not in our sprint, we can discuss it for future cases. Please leave comments blow.

**Comment by bwanglzu** [comment]
See this one https://github.com/faneshion/MatchZoo/blob/feature/examples/examples/wikiqa/run_dssm.ipynb
