### ISSUE TITLE
Is pip install matchzoo from pypi workable?

### ISSUE THREAD

**Issue by hkvision** [NTSC-Community/MatchZoo#341]
I saw matchzoo on pypi: https://pypi.org/project/MatchZoo/
and I use `pip install matchzoo` to install it.
But when I run ```from matchzoo.inputs.preprocess import *``` after installation, it throws the following error:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kai/anaconda2/envs/ms-py27/lib/python2.7/site-packages/matchzoo/inputs/__init__.py", line 6, in <module>
    from .point_generator import PointGenerator
  File "/home/kai/anaconda2/envs/ms-py27/lib/python2.7/site-packages/matchzoo/inputs/point_generator.py", line 8, in <module>
    from utils.rank_io import *
ImportError: No module named utils.rank_io
```

**Comment by bwanglzu** [comment]
@hkvision not yet, it's' created as a "placeholder". It will be there  as 2.0 being released.

**Comment by hkvision** [comment]
Then will the instructions here using setup.py work: https://github.com/faneshion/MatchZoo#installation? I doubt if I use this way, it will still throw the above error.

**Comment by bwanglzu** [comment]
@hkvision which os?

**Comment by hkvision** [comment]
I'm using Ubuntu 16.04 and tried python 2.7 and 3.5, but using the master code...
I saw your reply in my PR, do you recommend me to use branch 2.0? Since I'm trying the master code from the very beginning and I notice master and branch 2.0 differ quite a lot...

**Comment by bwanglzu** [comment]
@hkvision yes. there're several issues in the master branch, so we decided to develop the brand new Matchzoo (almost) from starch.
2.0 is still under development, only DSSM is available.

As you might know this project is maintained by a group of students, so we'll only fix bugs for 1.0, and devote ourselves on 2.0.
I'll create a virtualenv to check the setup and your pr.

**Comment by hkvision** [comment]
Okay I see. My PR only modifies something minor so that I can run the master code after cloning the repo, which should be of low priority.
It will be nice if the master code can be installed and run successfully to user environment using setup.py.
Thanks so much for tracking this and I'm glad for help if modifications needed to support the setup.

**Comment by bwanglzu** [comment]
@hkvision can you try to add the python path to environment variables?
use:
```shell
export PYTHONPATH=$PYTHONPATH:/YOUR-PATH-TO/MATCHZOO
```

**Comment by hkvision** [comment]
Emmm... After pip install I suppose matchzoo will be in the environment's sys.path? Let me have a try again probably.
